# Generated by Django 5.0.3 on 2024-03-17 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ThesisSearch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('thesis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='ThesisSearch.thesis')),
            ],
        ),
    ]
